/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "system-ui", "-apple-system", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      colors: {
        brand: {
          50: "#EFF6FF",
          100: "#DBEAFE",
          200: "#BFDBFE",
          300: "#93C5FD",
          400: "#60A5FA",
          500: "#3B82F6",
          600: "#2563EB",
          700: "#1D4ED8",
          800: "#1E40AF",
          900: "#1E3A8A",
        },
        surface: {
          0: "#0B0F19",
          50: "#0F1623",
          100: "#131926",
          200: "#1A2234",
          300: "#243044",
          400: "#334155",
        },
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "gradient-brand": "linear-gradient(135deg, #3B82F6 0%, #8B5CF6 100%)",
        "gradient-subtle":
          "linear-gradient(180deg, rgba(59,130,246,0.03) 0%, transparent 100%)",
      },
      boxShadow: {
        glow: "0 0 20px rgba(59,130,246,0.15)",
        "glow-lg": "0 0 40px rgba(59,130,246,0.2)",
        card: "0 1px 3px rgba(0,0,0,0.2), 0 1px 2px rgba(0,0,0,0.1)",
        "card-hover":
          "0 4px 12px rgba(0,0,0,0.3), 0 2px 4px rgba(0,0,0,0.15)",
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-out",
        "slide-up": "slideUp 0.3s ease-out",
        "slide-down": "slideDown 0.2s ease-out",
        "scale-in": "scaleIn 0.2s ease-out",
        "spin-slow": "spin 3s linear infinite",
        pulse: "pulse 2s cubic-bezier(0.4,0,0.6,1) infinite",
        shimmer: "shimmer 2s infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      borderRadius: {
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.25rem",
      },
      transitionDuration: {
        250: "250ms",
        350: "350ms",
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    logs: false,
    themes: [
      {
        shareify: {
          primary: "#3B82F6",
          "primary-content": "#FFFFFF",
          secondary: "#1E293B",
          "secondary-content": "#E2E8F0",
          accent: "#8B5CF6",
          "accent-content": "#FFFFFF",
          neutral: "#0F172A",
          "neutral-color": "#94A3B8",
          "base-100": "#0B0F19",
          "base-200": "#131926",
          "base-300": "#1E293B",
          "base-content": "#E2E8F0",
          info: "#38BDF8",
          "info-content": "#0C1420",
          success: "#10B981",
          "success-content": "#FFFFFF",
          warning: "#F59E0B",
          "warning-content": "#1C1405",
          error: "#EF4444",
          "error-content": "#FFFFFF",
          "--rounded-box": "0.75rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "0.375rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.97",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
          "--card-border": "1px",
        },
      },
      {
        "shareify-light": {
          primary: "#1D4ED8",
          "primary-content": "#FFFFFF",
          secondary: "#E2E8F0",
          "secondary-content": "#0F172A",
          accent: "#7C3AED",
          "accent-content": "#FFFFFF",
          neutral: "#F1F5F9",
          "neutral-color": "#475569",
          "base-100": "#FFFFFF",
          "base-200": "#F8FAFC",
          "base-300": "#E2E8F0",
          "base-content": "#0F172A",
          info: "#0284C7",
          "info-content": "#FFFFFF",
          success: "#047857",
          "success-content": "#FFFFFF",
          warning: "#B45309",
          "warning-content": "#FFFFFF",
          error: "#DC2626",
          "error-content": "#FFFFFF",
          "--rounded-box": "0.75rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "0.375rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.97",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
          "--card-border": "1px",
        },
      },
    ],
    darkTheme: "shareify",
  },
};
